spring.application.name=shop


spring.datasource.url=jdbc:postgresql://localhost:5433/shopdb_springboot_learning
spring.datasource.username=shopuser
#WTF ? Is it a joke? Please change it to something more secure in production!
# This is here just for testing and learning purposes, so it's not a big deal, I hope :) .
spring.datasource.password=shoppassword

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=online_shop

spring.flyway.schemas=online_shop
spring.flyway.default-schema=online_shop

